### ISSUE TITLE
Looking for a wrong version

### ISSUE THREAD

**Issue by Chozermith** [ExtremeMakerX/MTR-London-Underground-Trains#1]
Currently, a mod, which this addon is linked to, has its latest version at 3.2.2 while mod requires for a mod version to be 4.0.0
![Знімок екрана 2024-06-16 192008](https://github.com/ExtremeMakerX/MTR-London-Underground-Trains/assets/172991311/76b34ccc-6864-4f13-b460-55175de6d71e)

**Comment by ExtremeMakerX** [comment]
Which loader and version of LU Trains Mod are you using?

**Comment by ExtremeMakerX** [comment]
I will fix this problem soon!
Thanks for the bug report.

**Comment by Chozermith** [comment]
Could you update me when this bug gets fixed, please?

**Comment by ExtremeMakerX** [comment]
Hello Chozermith, could you download one of the Artifacts to see if the issue is fixed:
https://github.com/ExtremeMakerX/MTR-London-Underground-Trains/actions/runs/10048779487

Thank you!

**Comment by AmandaBjur** [comment]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Minecraft Transit Railway' (mtr) 4.0.0-beta.15 with any version between 4.0.0-beta-11 (inclusive) and 4.1 (exclusive).
More details:
	 - Mod 'MTR London Underground Trains' (londonundergroundtrains) 1.0.1 requires any version between 4.0.0-beta-11 (inclusive) and 4.1 (exclusive) of mod 'Minecraft Transit Railway' (mtr), but only the wrong version is present: 4.0.0-beta.15!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ExtremeMakerX** [comment]
Sorry for the late notice, but this has been solved in LU Addon Trains 1.0.2
